### ISSUE TITLE
Error when petbattling

### ISSUE THREAD

**Issue by laric** [GurliGebis/WoWAddon-PokemonTrainerNG#3]
Getting this error on 10.1.5

13x PokemonTrainer/Modules/FrameCombatDisplay.lua:914: attempt to index field 'animOut' (a nil value)
[string "@PokemonTrainer/Modules/FrameCombatDisplay.lua"]:914: in function <PokemonTrainer/Modules/FrameCombatDisplay.lua:908>
[string "@PokemonTrainer/Modules/FrameCombatDisplay.lua"]:934: in function <PokemonTrainer/Modules/FrameCombatDisplay.lua:927>
[string "@PokemonTrainer/Modules/FrameCombatDisplay.lua"]:966: in function <PokemonTrainer/Modules/FrameCombatDisplay.lua:964>
[string "@PokemonTrainer/Modules/FrameCombatDisplay.lua"]:1006: in function `BattleFrame_UpdateAbilityHighlights'
[string "@PokemonTrainer/Modules/FrameCombatDisplay.lua"]:262: in function <PokemonTrainer/Modules/FrameCombatDisplay.lua:250>
[string "=[C]"]: ?
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:69: in function <Ace3/AceBucket-3.0/AceBucket-3.0.lua:67>
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:83: in function `func'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
glow = PTGlowFrame1 {
 0 = <userdata>
 ProcLoop = AnimationGroup {
 }
 OnHide = <function> defined @FrameXML/ActionButton.lua:904
 ProcStartAnim = AnimationGroup {
 }
 ProcLoopFlipbook = Texture {
 }
 ProcStartFlipbook = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined @Paste/libs/LibStrataFix/LibStrataFix.lua:121
(*temporary) = "Frame"
(*temporary) = "attempt to index field 'animOut' (a nil value)"
table = <table> {
 setn = <function> defined =[C]:-1
 insert = <function> defined =[C]:-1
 getn = <function> defined =[C]:-1
 foreachi = <function> defined =[C]:-1
 maxn = <function> defined =[C]:-1
 foreach = <function> defined =[C]:-1
 concat = <function> defined =[C]:-1
 sort = <function> defined =[C]:-1
 removemulti = <function> defined =[C]:-1
 zygor_join = <function> defined @ZygorGuidesViewer/Functions.lua:13
 wipe = <function> defined =[C]:-1
 remove = <function> defined =[C]:-1
}
heap = <table> {
}
glownum = 1
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 AchievementFrameStatsBG = AchievementFrameStatsBG {
 }
 ARKINV_Frame4ChangerWindowPurchaseInfoDetailMoneyFrameCopperButtonText = ARKINV_Frame4ChangerWindowPurchaseInfoDetailMoneyFrameCopperButtonText {
 }
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 774
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 417
 BT4Button58 = BT4Button58 {
 }
 PawnItemComparer = <function> defined @Pawn/Pawn.lua:4055
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 LFGListInviteDialog_OnEvent = <function> defined @FrameXML/LFGList.lua:2774
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 UltraSquirtFrameReviveBattlePetsButtonCooldown = UltraSquirtFrameReviveBattlePetsButtonCooldown {
 }
 ArenaEnemyMatchFrame5PetFrameDropDownMiddle = ArenaEnemyMatchFrame5PetFrameDropDownMiddle {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML/UnitFrame.lua:927
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 WorldQuestTrackerWorldMapPOIWorldQuestTrackerWorldSummarySquarePOI2BorderShineAnimation3 = WorldQuestTrackerWorldMapPOIWorldQuestTrackerWorldSummarySquarePOI2BorderShineAnimation3 {
 }
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 GetMonitorAspectRatio = <function> defined =[C]:-1
 ToggleEncounterJournal = <function> defined @FrameXML/UIParent.lua:1136
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 Boss1TargetFrameValue = Boss1TargetFrameValue {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Default Shopping List"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 ARKINV_Frame4TitleActionButton2 = ARKINV_Frame4TitleActionButton2 {
 }
 Is64BitClient = <function> defined =[C]:-1
 TitanPanelVolumeControlFrameDialogTitle = TitanPanelVolumeControlFrameDialogTitle {
 }
 MultiBar5Button11Shine4 = MultiBar5Button11Shine4 {
 }
 TutorialFrame_OnMouseDown = <function> defined @FrameXML/Tutori

**Comment by cgsub** [comment]
Same issue, when battling the orb pet in Tyr Hold, every action you get that.
Somehow the glow doesn't get created, maybe because there's just one pet ?

Didn't really investigate further. 
I'm not doing much pvp battles so I don't really need those frames anyway...

**Comment by kcoderhere** [comment]
Also getting this error in 10.2 using the latest version v10.2.0-20231108_1:


Date: 2023-11-08 18:50:32
ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua line 914:
   attempt to index field 'animOut' (a nil value)
Debug:
   [string "@Interface/AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua"]:914:
      ...AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua:908
   [string "@Interface/AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua"]:934:
      ...AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua:927
   [string "@Interface/AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua"]:966:
      ...AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua:964
   [string "@Interface/AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua"]:1006: BattleFrame_UpdateAbilityHighlights()
   [string "@Interface/AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua"]:263:
      ...AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua:250
   [string "=[C]"]: ?
   [string "@Interface/AddOns/BattlePetCompletionist/Libs/AceBucket-3.0/AceBucket-3.0.lua"]:69:
      ...etCompletionist/Libs/AceBucket-3.0/AceBucket-3.0.lua:67
   [string "@Interface/AddOns/BattlePetCompletionist/Libs/AceBucket-3.0/AceBucket-3.0.lua"]:83: func()
   [string "@Interface/AddOns/BattlePetCompletionist/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:57:
      ...ePetCompletionist/Libs/AceTimer-3.0/AceTimer-3.0.lua:50
Locals:
glow = PTGlowFrame1 {
 0 = <userdata>
 ProcLoop = AnimationGroup {
 }
 OnHide = <function> defined @Interface/FrameXML/ActionButton.lua:936
 ProcStartAnim = AnimationGroup {
 }
 ProcLoopFlipbook = Texture {
 }
 ProcStartFlipbook = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined @Interface/AddOns/Outfitter/Libraries/LibTipHooker-1.1.lua:247
(*temporary) = "Frame"
(*temporary) = "attempt to index field 'animOut' (a nil value)"
table = <table> {
 setn = <function> defined =[C]:-1
 insert = <function> defined =[C]:-1
 getn = <function> defined =[C]:-1
 foreachi = <function> defined =[C]:-1
 maxn = <function> defined =[C]:-1
 foreach = <function> defined =[C]:-1
 concat = <function> defined =[C]:-1
 removemulti = <function> defined =[C]:-1
 sort = <function> defined =[C]:-1
 wipe = <function> defined =[C]:-1
 remove = <function> defined =[C]:-1
}
heap = <table> {
}
glownum = 1
_G = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 SLASH_ACECONSOLE_SETVIEW1 = "/setview"
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 775
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 417
 XPerl_AssistsView_Close = <function> defined @Interface/AddOns/ZPerl_RaidHelper/ZPerl_AssistFrame.lua:118
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 371
 MerchantItem4AltCurrencyFrameItem1Text = MerchantItem4AltCurrencyFrameItem1Text {
 }
 OPTION_SHOW_ACTION_BAR5_TOOLTIP = "Attached to the left side of Action Bar 4 by default"
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface/FrameXML/UnitFrame.lua:943
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 ERR_NOAMMO_S = "%s"
 RematchGameTooltipTexture13 = RematchGameTooltipTexture13 {
 }
 MoneyFrame_OnEvent = <function> defined @Interface/FrameXML/MoneyFrame.lua:202
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 996
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ToggleEncounterJournal = <function> defined @Interface/FrameXML/UIParent.lua:1130
 TrinketMenu_Trinket1Shine13 = TrinketMenu_Trinket1Shine13 {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 XPerl_Raid_Grp10UnitButton1buffFrame = XPerl_Raid_Grp10UnitButton1buffFrame {
 }
 MacroFrame = MacroFrame {
 }
 Boss1TargetFrameValue = Boss1TargetFrameValue {
 }
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 XPERL_RAID_TOOLTIP_BUFFEXPIRING = "%s's %s expires in %s"
 Is64BitClient = <function> defined =[C]:-1
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle {
 }
 TutorialFrame_OnMouseDown = <function> defined @Interface/FrameXML/TutorialFrame.lua:262
 ContainerFrame4Item16Cooldown = ContainerFrame4Item16Cooldown {
 }
 LE_GAME_ERR_AZERITE_ESSENCE_SELECTION_FAILED_ESSENCE_NOT_UNLOCKED = 1063
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 PlayerFrame_UpdateReadyCheck = <function> defined @Interface/FrameXML/PlayerFrame.lua:419
 L = <table> {
 }
 NamePlate8PlaterUnitFramesoftInteractIconFrameIcon = NamePlate8PlaterUnitFramesoftInteractIconFrameIcon {
 }
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 SPELL_FAILED_CUSTOM_ERROR_152 = "You must choose a specialization to use Ascendance."
 LAG_TOLERANCE = "Lag

**Comment by GurliGebis** [comment]
Is this still an issue in 10.2.6?
I just tried enabling animations again, and it seems to be working on my machine (I know it was broken earlier - I wonder if it was something that was broken silently and then repaired silently).

**Comment by GurliGebis** [comment]
Could you please try `10.2.6-20240430-1`, which I just released a few minutes ago, and see if it works with that?

**Comment by laric** [comment]
I don't seem to be getting the animation errors anymore.
