### ISSUE TITLE
When clicking on "Enable" in "HealPet Buttons" 

### ISSUE THREAD

**Issue by alar77** [GurliGebis/WoWAddon-PokemonTrainerNG#5]
`l1x PokemonTrainer/Modules/HealBandageButtons.lua:81: attempt to call field 'GetNumTrackingTypes' (a nil value)

[string "@PokemonTrainer/Modules/HealBandageButtons.lua"]:81: in function `CheckMinimapTracking'

[string "@PokemonTrainer/Modules/HealBandageButtons.lua"]:52: in function <PokemonTrainer/Modules/HealBandageButtons.lua:47>

[string "=[C]"]: ?

[string "@ItemLevelDisplay/libs/LibInit-73/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...play/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>

[string "@ItemLevelDisplay/libs/LibInit-73/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function <...play/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:516>

[string "=(tail call)"]: ?

[string "=(tail call)"]: ?

[string "=[C]"]: ?

[string "@ItemLevelDisplay/libs/LibInit-73/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>

[string "@ItemLevelDisplay/libs/LibInit-73/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>

[string "=[C]"]: ?

[string "@ItemLevelDisplay/libs/LibInit-73/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...lDisplay/libs/LibInit/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>

[string "@ItemLevelDisplay/libs/LibInit-73/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'

[string "@ItemLevelDisplay/libs/LibInit-73/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...it/Ace3/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

 

Locals:

self = <table> {

 Button_UpdateCooldown = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:127

 SetDefaultModuleLibraries = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363

 Enable = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290

 UnregisterAllEvents = <function> defined @BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164

 EnableModule = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328

 modules = <table> {

 }

 GetModule = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:206

 IterateEmbeds = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438

 defaultModuleLibraries = <table> {

 }

 Button_UpdateUsability = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:139

 SetDraggable = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:100

 SetDefaultModulePrototype = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405

 desc = "When pet tracking is enabled, this module displays two buttons on a separate and draggable frame. One for healing your battle pets with the spellcast, another for healing with pet bandages. Clicking these buttons is allowed when not in combat."

 name = "PokemonTrainer_HealBandageButtons"

 IsEnabled = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447

 orderedModules = <table> {

 }

 DisableModule = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346

 RegisterMessage = <function> defined @BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80

 UnregisterMessage = <function> defined @BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143

 CombatEvent = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:67

 baseName = "PokemonTrainer"

 GetOptions = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:181

 SetBindings = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:111

 CheckMinimapTracking = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:78

 IsModule = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:213

 db = <table> {

 }

 SetDefaultModuleState = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:383

 OnDisable = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:55

 OnEnable = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:47

 SetEnabledState = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420

 OnInitialize = <function> defined @PokemonTrainer/Modules/HealBandageButtons.lua:26

 enabledState = true

 petBandage = 86143

 RegisterEvent = <function> defined @BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80

 UnregisterAllMessages = <function> defined @BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164

 SendMessage = <function> defined @BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49

 displayName = "Heal Pet Buttons"

 defaultModuleState = true

 IterateModules = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:433

 NewModule = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:231

 GetName = <function> defined @ItemLevelDisplay/libs/LibInit/Ace3/AceAddon-3.0/AceAddon-3.0.lua:275

 petHealSpell = 125439

 moduleName = "HealBandageButtons"`

**Comment by GurliGebis** [comment]
This should be resolved in `10.2.6-20240430-1`, which I just released a few minutes ago.
