### ISSUE TITLE
PokemonTrainer Issue

### ISSUE THREAD

**Issue by SalientAnimal** [GurliGebis/WoWAddon-PokemonTrainerNG#6]
Message: ...AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua:914: attempt to index field 'animOut' (a nil value)

Time: Sun May  5 12:23:47 2024

Count: 15

Stack: ...AddOns/PokemonTrainer/Modules/FrameCombatDisplay.lua:914: attempt to index field 'animOut' (a nil value)

**Comment by GurliGebis** [comment]
The issue is due to Blizzard changing the entire animation logic in 10.1.5 .
For now, I have disabled those animations, to prevent the errors, until I can find a solution.
I have pushed `10.2.7-20240513_1`, which has this change, and will remove the errors.
