### ISSUE TITLE
Last Patch Mouse over a guard

### ISSUE THREAD

**Issue by deksan** [GurliGebis/WoWAddon-PokemonTrainerNG#7]
Message: ...ace/AddOns/PokemonTrainer/Modules/WildPetTooltip.lua:73: attempt to index field 'db' (a nil value)
Time: Wed Aug 14 07:11:03 2024
Count: 32
Stack: ...ace/AddOns/PokemonTrainer/Modules/WildPetTooltip.lua:73: attempt to index field 'db' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/PokemonTrainer/Modules/WildPetTooltip.lua"]:73: in function `?'
[string "@Interface/AddOns/Altoholic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Altoholic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Altoholic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:

**Comment by GurliGebis** [comment]
Hey,

I'm looking into it - it seems like some of the libraries the addon uses is causing problems.

**Comment by GurliGebis** [comment]
I just pushed a new version, hopefully that helps with the issues.

**Comment by GurliGebis** [comment]
Closing the ticket, please let me know if the issue shows up again.
